server {
    listen 80; # Слушаем порт 80 внутри контейнера
    server_tokens off; # Скрываем версию Nginx в заголовках ответа (безопасность)
    client_max_body_size 10M; # Разрешаем загружать файлы размером до 10 Мб
    index index.html;

    # Проксирование запросов к API на бэкенд
    location /api/ {
        proxy_set_header Host $http_host; # Передаём оригинальный хост
        proxy_pass http://backend:9999/api/; # Перенаправляем запрос на контейнер backend
    }

    # Проксирование запросов к админке на бэкенд
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    # Раздача медиафайлов (картинки пользователей)
    location /media/ {
        alias /media/; # Файлы лежат в папке /media/ внутри контейнера gateway
    }

    # Раздача статики и фронтенда
    location / {
        alias /static/; # Файлы лежат в папке /static/ внутри контейнера gateway
        try_files $uri $uri/ /index.html; # Если файл не найден, отдаём index.html
    }
}